# Generated by Django 4.1.3 on 2022-12-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="goles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("goles", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="jugadores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("puesto", models.CharField(max_length=20)),
                ("camiseta", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="partidos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rival", models.CharField(max_length=50)),
                ("instancia", models.CharField(max_length=50)),
                ("resultado", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="tecnicos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("rol", models.CharField(max_length=25)),
            ],
        ),
    ]
