# Generated by Django 4.1.3 on 2022-12-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appUno", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goles",
            name="apellido",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="jugadores",
            name="apellido",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
