# Generated by Django 4.1.3 on 2022-12-20 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appUno", "0002_goles_apellido_jugadores_apellido"),
    ]

    operations = [
        migrations.RemoveField(model_name="goles", name="apellido",),
        migrations.RemoveField(model_name="jugadores", name="apellido",),
    ]
